### ISSUE TITLE
arrow module

### ISSUE THREAD

**Issue by ghost** [wrycu/srs_recorder#15]
Hello, when I try to run it, it tells me that the arrow module is missing. I have tried to run it with the phyton idle itself and with pycharm, but the result is the same.

**Comment by ghost** [comment]
Sorry, I was just adding it

**Comment by wrycu** [comment]
You'll want to `pip install -r requirements.txt` - all package requirements are included [here](https://github.com/wrycu/srs_recorder/blob/main/requirements.txt).
