### ISSUE TITLE
SRS_Recorder not loading

### ISSUE THREAD

**Issue by harryer46** [wrycu/srs_recorder#18]
We were looking for a tool like this, but we were not able to get it running

When restarting the server mission only the log of the time of restart is written

`Sat Dec  4 20:46:47 2021 | SRS_RECORDER loading`

**Comment by wrycu** [comment]
Looks like the lua script hit some kind of error. I've been meaning to port the DCS triggering functionality to [DCS-gRPC](https://github.com/DCS-gRPC/rust-server) anyway, so rather than debug this, I'll work on getting that port done.

**Comment by wrycu** [comment]
swapped to DCS-gRPC.
